version: "1.0"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_vector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgvector_db
    ports:
      - "4444:5432"
    volumes:
      - postgres_vector_data:/var/lib/postgresql/data
    networks:
      - postgres_vector_network

volumes:
  postgres_vector_data:

networks:
  postgres_vector_network:
    driver: bridge
